version = "1.1.16"

[class]
obsidian = "î®¯"
feishin = "â™«"
mpv = "îšŸ"
"[Ff]irefox" = "ï‰©"
BambuStudio = "ó°¹œ"
nemo = "îªƒ"
floorp = "ï’ˆ"
zen = "ï’ˆ"
"[Ff]irefoxdeveloperedition" = "ï‰©"
steam = "ï†¶"
virt-manager = "î®©"
Bitwarden = "ó°€"
remmina = "ó°¢¹"
discord = "ó°™¯"
"[Tt]hunderbird" = "î¬œ"
"com.usebottles.bottles" = "ó±£"
DEFAULT = "ï™"
"battle.net.exe" = "ï µ"
"(?i)minecraft" = "ó°³"
Code = "ó°¨"
Vivaldi = "ï’ˆ"
"(?i)Kitty" = "ï„ "
"(?i)waydroid.*" = "droid"
whatsdesk = "ïˆ²"

[class_active]
DEFAULT = "{class}"
"(?i)ExampleOneTerm" = "<span foreground='red'>{icon}</span>"

[initial_class]

[initial_class_active]

[workspaces_name]
6 = "six"
0 = "zero"
4 = "four"
2 = "two"
9 = "nine"
3 = "three"
5 = "five"
8 = "eight"
1 = "one"
10 = "ten"
7 = "seven"

[title_in_class."(?i)kitty"]
"(?i)neomutt" = "neomutt"

[title_in_class."(?i)firefox"]
"(?i)youtube" = "ï…ª"
"(?i)holdem" = "ğŸƒ"
"(?i)navidrome" = "â™«"
"(?i)twitch" = "ï‡¨"
"(?i)poker" = "ğŸƒ"

[title_in_class_active."(?i)firefox"]
"(?i)youtube" = "ï…ª"
"(?i)poker" = "ğŸƒ"
"(?i)navidrome" = "â™«"
"(?i)twitch" = "ï‡¨"
"(?i)holdem" = "ğŸƒ"

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"battle.net.exe" = "explorer.exe"
aProgram = "^$"
"(?i)TestApp" = ""
"(?i)fcitx" = ".*"
"" = "^$"
"[Ss]team" = "^(Friends List.*)?$"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
workspace = "{id}: {clients}"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "[{icon}]"
client_active = "{icon}"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
